version: '2'
services:
  jhipstertest1-app:
    image: jhipstertest1
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipstertest1-postgresql:5432/jhipsterTest1
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipstertest1-postgresql:
    extends:
      file: postgresql.yml
      service: jhipstertest1-postgresql
